baseURL = "https://defaria.io/"
title = "cto ♥️ data | ml | devops"
theme = "hugo-coder"
languageCode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
    author = "Thiago de Faria"
    info = "CTO ♥ Data | ML | devops"
    description = "Thiago de Faria's personal website"
    keywords = "devops, AI, ML, mlops, data"
    avatarurl = "images/avatar.jpg"

    dateformat = "January 2, 2006"

    hideFooter = true
    hidecredits = false
    hidecopyright = false
    since = 2020
 
    colorscheme = "dark"
 
    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true


# Social links
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/thiagoavadore/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/thiagoavadore/"

# Menu links
[[menu.main]]
    name = "Speaking"
    weight = 1
    url = "speaking/"
[[menu.main]]
    name = "Posts"
    weight = 2
    url = "posts/"
[[menu.main]]
    name = "Contact me"
    weight = 3
    url = "contact/"
